# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cbind_val_cpp <- function(val, x) {
    .Call(`_bcn_cbind_val_cpp`, val, x)
}

colsums_cpp <- function(x) {
    .Call(`_bcn_colsums_cpp`, x)
}

crossprod_cpp <- function(x, y) {
    .Call(`_bcn_crossprod_cpp`, x, y)
}

columns_crossprod_cpp <- function(eL) {
    .Call(`_bcn_columns_crossprod_cpp`, eL)
}

squared_crossprod_cpp <- function(eL, hL) {
    .Call(`_bcn_squared_crossprod_cpp`, eL, hL)
}

calculate_xsiL_cpp <- function(eL, hL, nu, r, L) {
    .Call(`_bcn_calculate_xsiL_cpp`, eL, hL, nu, r, L)
}

calculate_hL_cpp <- function(x, w, activation) {
    .Call(`_bcn_calculate_hL_cpp`, x, w, activation)
}

calculate_xsiL <- function(eL, hL, nu, r, L) {
    .Call(`_bcn_calculate_xsiL`, eL, hL, nu, r, L)
}

calculate_betasL <- function(eL, hL) {
    .Call(`_bcn_calculate_betasL`, eL, hL)
}

calculate_fittedeL <- function(betasL, hL, nu) {
    .Call(`_bcn_calculate_fittedeL`, betasL, hL, nu)
}

rcpp_hello_world <- function() {
    .Call(`_bcn_rcpp_hello_world`)
}

